---
title: "Making Maps"
author: "Dr. Mine Dogucu"
output: 
  xaringan::moon_reader:
    css: ["slide-style.css"]
    seal: false
    nature:
      ratio: 16:9
      highlightStyle: "pygments"
      highlightLines: true
      highlightLanguage: "r"
---

class: title-slide


<br>
<br>
.right-panel[ 

# `r rmarkdown::metadata$title`
## `r rmarkdown::metadata$author`
]

---

```{r echo = FALSE, message = FALSE}
library(tidyverse)


```

```{r message = FALSE}
library(maps)
usa <- map_data("usa")
glimpse(usa)
```

---

.pull-left[
<br>
<br>
<br>
```{r fig.align='center', eval = FALSE}
ggplot(data = usa,
       aes(x = long, 
           y = lat)) 
```
]

.pull-right[

```{r fig.align='center', echo = FALSE}
ggplot(data = usa,
       aes(x = long, 
           y = lat))
```
]
---
.pull-left[
<br>
<br>
<br>
```{r fig.align='center', eval = FALSE}
ggplot(data = usa,
       aes(x = long, 
           y = lat)) + 
  geom_polygon() 
```
]

.pull-right[

```{r fig.align='center', echo = FALSE}
ggplot(data = usa,
       aes(x = long, 
           y = lat)) + 
  geom_polygon() 

```
]
---
.pull-left[
<br>
<br>
<br>
```{r fig.align='center', eval = FALSE}
ggplot(data = usa,
       aes(x = long, 
           y = lat)) + 
  geom_polygon() + 
  coord_fixed(1.4)
```
]

.pull-right[

```{r fig.align='center', echo = FALSE}
ggplot(data = usa,
       aes(x = long, 
           y = lat)) + 
  geom_polygon() + 
  coord_fixed(1.4)
```
]
---
.pull-left[
<br>
<br>
<br>
```{r fig.align='center', eval = FALSE}
ggplot(data = usa,
       aes(x = long, 
           y = lat)) + 
  geom_polygon(fill = NA,
               color = "steelblue") + 
  coord_fixed(1.4)
```
]

.pull-right[

```{r fig.align='center', echo = FALSE}
ggplot(data = usa,
       aes(x = long, 
           y = lat)) + 
  geom_polygon(fill = NA, 
               color = "steelblue") + 
  coord_fixed(1.4)
```
]

---
.pull-left[
<br>
<br>
<br>
```{r fig.align='center', eval = FALSE}
ggplot(data = usa,
       aes(x = long, 
           y = lat)) + 
  geom_polygon(fill = NA, 
               color = "steelblue",
               aes(group = group))  + 
  coord_fixed(1.4)
```
]

.pull-right[

```{r fig.align='center', echo = FALSE}
ggplot(data = usa,
       aes(x = long, 
           y = lat)) + 
  geom_polygon(fill = NA, 
               color = "steelblue",
               aes(group = group))  + 
  coord_fixed(1.4)
```
]

---

```{r}
location <- c("Northampton", "Columbus", "Sarasota","Irvine" )
  
long <- c(-72.6412, -82.998795, -82.538602, -117.824719)

lat <- c(42.3251, 39.961178, 27.336483, 33.685908)

pop <- c(28726, 892533, 57738, 282572)
         

home <- tibble::tibble(location = location,
                 lat = lat,
                 long = long,
                 pop = pop)
```

---

```{r}
home
```

---

.pull-left[
<br>
<br>
<br>
```{r fig.align='center', eval = FALSE}
usa_map <- 
  ggplot(data = usa,
         aes(x = long, 
             y = lat)) + 
  geom_polygon(fill = NA, color = "steelblue",
               aes(group = group)) + 
  coord_fixed(1.4)
```
]

.pull-right[

```{r fig.align='center', echo = FALSE}
usa_map <-
  ggplot(data = usa,
       aes(x = long, 
           y = lat)) + 
  geom_polygon(fill = NA, 
               color = "steelblue",
               aes(group = group))  + 
  coord_fixed(1.4)
```
]


---

.pull-left[
<br>
<br>
<br>
```{r fig.align='center', eval = FALSE}
usa_map +
  geom_point(data = home, 
             aes(x = long,
                 y = lat, 
                 color = pop))
```
]

.pull-right[

```{r fig.align='center', echo = FALSE}
usa_map +
  geom_point(data = home, 
             aes(x = long,
                 y = lat, 
                 color = pop))
```
]

---

.pull-left[
<br>
<br>
<br>
```{r fig.align='center', eval = FALSE}
usa_map +
  geom_point(data = home, 
             aes(x = long,
                 y = lat, 
                 size = pop))
```
]

.pull-right[

```{r fig.align='center', echo = FALSE}
usa_map +
  geom_point(data = home, 
             aes(x = long,
                 y = lat, 
                 size = pop))
```
]

---

.pull-left[
<br>
<br>
<br>
```{r fig.align='center', eval = FALSE}
states <- map_data("state")
ggplot(data = states,
       aes(x = long, 
           y = lat,
           fill = region)) + 
  geom_polygon(aes(group = group))  + 
  coord_fixed(1.4) +
  guides(fill = FALSE)
```
]

.pull-right[

```{r fig.align='center', echo = FALSE}
states <- map_data("state")
ggplot(data = states,
       aes(x = long, 
           y = lat,
           fill = region)) + 
  geom_polygon(aes(group = group))  + 
  coord_fixed(1.4) +
  guides(fill = FALSE)
```
]


---

`library(sf)`

[Maps Chapter from ggplot2 book](https://ggplot2-book.org/maps.html)

